package com.myspace.persist;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Employee implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(generator = "EMPLOYEE_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "EMPLOYEE_ID_GENERATOR", sequenceName = "EMPLOYEE_ID_SEQ")
	private java.lang.Long id;

	private java.lang.String firstName;

	@org.kie.api.definition.type.Label(value = "LastName")
	private java.lang.String lastName;

	public Employee() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(java.lang.String firstName) {
		this.firstName = firstName;
	}

	public java.lang.String getLastName() {
		return this.lastName;
	}

	public void setLastName(java.lang.String lastName) {
		this.lastName = lastName;
	}

	public Employee(java.lang.Long id, java.lang.String firstName,
			java.lang.String lastName) {
		this.id = id;
		this.firstName = firstName;
		this.lastName = lastName;
	}

}